### ISSUE TITLE
entity.copy() =>numpy.hstack raise TypeError: invalid type promotion

### ISSUE THREAD

**Issue by MatthieuCMira** [MiraGeoscience/geoh5py#246] opened 2022-09-07 20:44 UTC
I am trying to copy an entity (let's say a drillhole) from a workspace to another.
I created a new DrillholeGroup in the destination workspace, which is a copy of the parent of the drillhole to copy

`new_drillhole = drillhole.copy(parent = new_DrillholeGroup)`

raises:
```

File "D:\git\geoh5py\geoh5py\shared\entity.py", line 185, in copy
    new_entity = parent.workspace.copy_to_parent(
  File "D:\git\geoh5py\geoh5py\workspace\workspace.py", line 267, in copy_to_parent
    new_object = parent.workspace.create_entity(
  File "D:\git\geoh5py\geoh5py\workspace\workspace.py", line 404, in create_entity
    self.save_entity(created_entity)
  File "D:\git\geoh5py\geoh5py\workspace\workspace.py", line 1116, in save_entity
    entity.concatenator.add_save_concatenated(entity)
  File "D:\git\geoh5py\geoh5py\shared\concatenation.py", line 112, in add_save_concatenated
    self.update_array_attribute(child, "surveys")
  File "D:\git\geoh5py\geoh5py\shared\concatenation.py", line 549, in update_array_attribute
    values = np.hstack([self.data[alias], values])
  File "<__array_function__ internals>", line 180, in hstack
  File "C:\Users\matthieuc\Anaconda3\envs\oxide_converter\lib\site-packages\numpy\core\shape_base.py", line 343, in hstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
  File "C:\Users\matthieuc\Anaconda3\envs\oxide_converter\lib\site-packages\numpy\core\_internal.py", line 458, in _promote_fields
    raise TypeError("invalid type promotion")
TypeError: invalid type promotion
```

It seems it's due to the dtype of the drillhole data (https://stackoverflow.com/questions/14944275/how-to-hstack-arrays-of-numpy-records)

Thanks,

Update:
same error raises for:
`drillhole.copy()`

**Comment by domfournier** [comment] 2023-03-15 21:19
Could not reproduce. Likely fixed by GEOPY-723

**Closed by domfournier** 2023-03-15 21:19 UTC
